org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties (from fabricmc.net/develop for 26.3)
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
version=0.1.0
group=com.prismultra.ghosts

fabric_api_version=0.161.0+26.3
voicechat_api_version=2.6.0
